#!/bin/bash
################################################################################
# Shell Plugins Module
# Auto-install and configure useful shell plugins
################################################################################

install_zsh_plugins() {
    log_info "Installing ZSH plugins..."
    
    local user_info
    user_info=$(get_user_info)
    local target_user="${user_info%%:*}"
    local target_home="${user_info#*:}"
    
    if [ "$DRY_RUN" = true ]; then
        log_info "[DRY-RUN] Would install ZSH plugins"
        return 0
    fi
    
    if [ ! -d "$target_home/.oh-my-zsh" ]; then
        log_warn "Oh-My-ZSH not installed. Install ZSH first."
        return 1
    fi
    
    local custom_dir="$target_home/.oh-my-zsh/custom"
    
    # Install zsh-autosuggestions
    if [ ! -d "$custom_dir/plugins/zsh-autosuggestions" ]; then
        log_info "Installing zsh-autosuggestions..."
        sudo -u "$target_user" git clone https://github.com/zsh-users/zsh-autosuggestions \
            "$custom_dir/plugins/zsh-autosuggestions"
    fi
    
    # Install zsh-syntax-highlighting (if not already installed)
    if [ ! -d "$custom_dir/plugins/zsh-syntax-highlighting" ]; then
        log_info "Installing zsh-syntax-highlighting..."
        sudo -u "$target_user" git clone https://github.com/zsh-users/zsh-syntax-highlighting \
            "$custom_dir/plugins/zsh-syntax-highlighting"
    fi
    
    # Install zsh-completions
    if [ ! -d "$custom_dir/plugins/zsh-completions" ]; then
        log_info "Installing zsh-completions..."
        sudo -u "$target_user" git clone https://github.com/zsh-users/zsh-completions \
            "$custom_dir/plugins/zsh-completions"
    fi
    
    # Install fzf-tab
    if [ ! -d "$custom_dir/plugins/fzf-tab" ]; then
        log_info "Installing fzf-tab..."
        sudo -u "$target_user" git clone https://github.com/Aloxaf/fzf-tab \
            "$custom_dir/plugins/fzf-tab"
    fi
    
    # Update .zshrc plugins
    local zshrc="$target_home/.zshrc"
    if [ -f "$zshrc" ]; then
        create_backup "$zshrc" "zshrc-plugins"
        
        # Enhanced plugin list
        local plugins="git docker kubectl terraform golang rust npm zsh-autosuggestions zsh-syntax-highlighting zsh-completions fzf-tab"
        
        sed -i "s/^plugins=.*/plugins=($plugins)/" "$zshrc"
        
        # Add fpath for completions
        if ! grep -q "fpath+=.*zsh-completions" "$zshrc"; then
            sed -i '/^source \$ZSH\/oh-my-zsh.sh/i fpath+=${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/plugins/zsh-completions/src' "$zshrc"
        fi
        
        log_success "ZSH plugins configured"
    fi
}

install_bash_enhancements() {
    log_info "Installing Bash enhancements..."
    
    local user_info
    user_info=$(get_user_info)
    local target_user="${user_info%%:*}"
    local target_home="${user_info#*:}"
    
    if [ "$DRY_RUN" = true ]; then
        log_info "[DRY-RUN] Would install Bash enhancements"
        return 0
    fi
    
    # Install bash-completion if not present
    if ! dpkg -l | grep -q bash-completion; then
        apt install -y bash-completion
    fi
    
    local bashrc="$target_home/.bashrc"
    if [ -f "$bashrc" ]; then
        create_backup "$bashrc" "bashrc-enhancements"
        
        # Add bash completion
        if ! grep -q "bash_completion" "$bashrc"; then
            cat >> "$bashrc" << 'EOF'

# Enable bash completion
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi
EOF
        fi
        
        log_success "Bash enhancements configured"
    fi
}

setup_custom_aliases() {
    log_info "Setting up custom aliases..."
    
    local user_info
    user_info=$(get_user_info)
    local target_user="${user_info%%:*}"
    local target_home="${user_info#*:}"
    
    if [ "$DRY_RUN" = true ]; then
        log_info "[DRY-RUN] Would setup custom aliases"
        return 0
    fi
    
    local aliases_file="$target_home/.bash_aliases"
    
    # Create aliases file
    sudo -u "$target_user" tee "$aliases_file" > /dev/null << 'EOF'
# Custom Aliases
# Generated by Pop!_OS Setup Script

# Navigation
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# List commands
alias ll='ls -lah'
alias la='ls -A'
alias l='ls -CF'

# Safety
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Git shortcuts
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git pull'
alias gd='git diff'
alias gco='git checkout'
alias gb='git branch'
alias glog='git log --oneline --graph --decorate'

# Docker shortcuts
alias dps='docker ps'
alias dpsa='docker ps -a'
alias di='docker images'
alias dex='docker exec -it'
alias dlog='docker logs -f'
alias dcu='docker-compose up -d'
alias dcd='docker-compose down'

# Kubernetes shortcuts
alias k='kubectl'
alias kgp='kubectl get pods'
alias kgs='kubectl get services'
alias kgd='kubectl get deployments'
alias kdp='kubectl describe pod'
alias kl='kubectl logs -f'

# System
alias update='sudo apt update && sudo apt upgrade -y'
alias cleanup='sudo apt autoremove -y && sudo apt autoclean'
alias ports='netstat -tulanp'

# Useful commands
alias myip='curl ifconfig.me'
alias weather='curl wttr.in'
alias speedtest='curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python3 -'

# Modern CLI tools (if installed)
if command -v exa &> /dev/null; then
    alias ls='exa'
    alias ll='exa -lah'
    alias tree='exa --tree'
fi

if command -v bat &> /dev/null; then
    alias cat='bat'
fi

if command -v btop &> /dev/null; then
    alias top='btop'
elif command -v htop &> /dev/null; then
    alias top='htop'
fi
EOF
    
    # Source aliases in .bashrc
    local bashrc="$target_home/.bashrc"
    if [ -f "$bashrc" ] && ! grep -q ".bash_aliases" "$bashrc"; then
        cat >> "$bashrc" << 'EOF'

# Load custom aliases
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi
EOF
    fi
    
    # Source aliases in .zshrc
    local zshrc="$target_home/.zshrc"
    if [ -f "$zshrc" ] && ! grep -q ".bash_aliases" "$zshrc"; then
        cat >> "$zshrc" << 'EOF'

# Load custom aliases
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi
EOF
    fi
    
    log_success "Custom aliases configured: $aliases_file"
}

configure_shell_theme() {
    log_info "Configuring shell theme..."
    
    local user_info
    user_info=$(get_user_info)
    local target_user="${user_info%%:*}"
    local target_home="${user_info#*:}"
    
    if [ "$DRY_RUN" = true ]; then
        log_info "[DRY-RUN] Would configure shell theme"
        return 0
    fi
    
    # For ZSH, we already set 'blinks' theme
    # Add Powerlevel10k as an option
    if [ -d "$target_home/.oh-my-zsh" ]; then
        local p10k_dir="$target_home/.oh-my-zsh/custom/themes/powerlevel10k"
        
        if ask_permission "Install Powerlevel10k theme for ZSH?"; then
            if [ ! -d "$p10k_dir" ]; then
                log_info "Installing Powerlevel10k..."
                sudo -u "$target_user" git clone --depth=1 \
                    https://github.com/romkatv/powerlevel10k.git "$p10k_dir"
                
                # Update theme in .zshrc
                local zshrc="$target_home/.zshrc"
                sed -i 's/^ZSH_THEME=.*/ZSH_THEME="powerlevel10k\/powerlevel10k"/' "$zshrc"
                
                log_success "Powerlevel10k installed"
                log_info "Run 'p10k configure' to customize your theme"
            else
                log_info "Powerlevel10k already installed"
            fi
        fi
    fi
}

install_shell_enhancements() {
    log_info "Installing shell enhancements..."
    
    # Install ZSH plugins if ZSH is installed
    if check_command zsh; then
        install_zsh_plugins
    fi
    
    # Install Bash enhancements
    install_bash_enhancements
    
    # Setup custom aliases
    setup_custom_aliases
    
    # Configure theme
    configure_shell_theme
    
    log_success "Shell enhancements complete"
    mark_installed "shell_plugins" "configured"
}
