#!/bin/bash
################################################################################
# SSH Automation Module
# Handles SSH key generation, configuration, and setup
################################################################################

generate_ssh_key() {
    log_info "Checking SSH key configuration..."
    
    local user_info
    user_info=$(get_user_info)
    local target_user="${user_info%%:*}"
    local target_home="${user_info#*:}"
    local ssh_dir="$target_home/.ssh"
    
    if [ "$DRY_RUN" = true ]; then
        log_info "[DRY-RUN] Would generate SSH key"
        return 0
    fi
    
    # Ensure .ssh directory exists
    sudo -u "$target_user" mkdir -p "$ssh_dir"
    chmod 700 "$ssh_dir"
    
    # Check if key already exists
    if [ -f "$ssh_dir/id_ed25519" ]; then
        log_info "SSH key already exists: $ssh_dir/id_ed25519"
        return 0
    fi
    
    log_info "Generating new SSH key (ed25519)..."
    
    # Get email for key comment
    local email
    email=$(sudo -u "$target_user" git config --global user.email 2>/dev/null || echo "$target_user@$(hostname)")
    
    # Generate key
    sudo -u "$target_user" ssh-keygen -t ed25519 -C "$email" -f "$ssh_dir/id_ed25519" -N ""
    
    log_success "SSH key generated: $ssh_dir/id_ed25519"
    log_info "Public key: $ssh_dir/id_ed25519.pub"
    
    # Display public key
    echo ""
    log_info "Your public key:"
    cat "$ssh_dir/id_ed25519.pub"
    echo ""
}

configure_ssh_client() {
    log_info "Configuring SSH client..."
    
    local user_info
    user_info=$(get_user_info)
    local target_user="${user_info%%:*}"
    local target_home="${user_info#*:}"
    local ssh_config="$target_home/.ssh/config"
    
    if [ "$DRY_RUN" = true ]; then
        log_info "[DRY-RUN] Would configure SSH client"
        return 0
    fi
    
    # Backup existing config
    if [ -f "$ssh_config" ]; then
        create_backup "$ssh_config" "ssh-config"
    fi
    
    # Create basic SSH config if it doesn't exist
    if [ ! -f "$ssh_config" ]; then
        sudo -u "$target_user" tee "$ssh_config" > /dev/null << 'EOF'
# SSH Client Configuration
# Generated by Pop!_OS Setup Script

# Global settings
Host *
    AddKeysToAgent yes
    IdentityFile ~/.ssh/id_ed25519
    ServerAliveInterval 60
    ServerAliveCountMax 3
    Compression yes

# GitHub
Host github.com
    HostName github.com
    User git
    IdentityFile ~/.ssh/id_ed25519

# GitLab
Host gitlab.com
    HostName gitlab.com
    User git
    IdentityFile ~/.ssh/id_ed25519

# Add your custom hosts below
# Host myserver
#     HostName example.com
#     User myuser
#     Port 22
#     IdentityFile ~/.ssh/id_ed25519
EOF
        chmod 600 "$ssh_config"
        log_success "SSH config created: $ssh_config"
    else
        log_info "SSH config already exists: $ssh_config"
    fi
}

setup_ssh_agent() {
    log_info "Configuring SSH agent..."
    
    local user_info
    user_info=$(get_user_info)
    local target_user="${user_info%%:*}"
    local target_home="${user_info#*:}"
    
    if [ "$DRY_RUN" = true ]; then
        log_info "[DRY-RUN] Would setup SSH agent"
        return 0
    fi
    
    # Add SSH agent configuration to shell profiles
    local agent_config='
# SSH Agent configuration
if [ -z "$SSH_AUTH_SOCK" ]; then
    eval "$(ssh-agent -s)" > /dev/null 2>&1
    ssh-add ~/.ssh/id_ed25519 2>/dev/null
fi
'
    
    # Add to .bashrc if not present
    if [ -f "$target_home/.bashrc" ] && ! grep -q "SSH Agent configuration" "$target_home/.bashrc"; then
        echo "$agent_config" >> "$target_home/.bashrc"
        log_success "SSH agent configured in .bashrc"
    fi
    
    # Add to .zshrc if not present
    if [ -f "$target_home/.zshrc" ] && ! grep -q "SSH Agent configuration" "$target_home/.zshrc"; then
        echo "$agent_config" >> "$target_home/.zshrc"
        log_success "SSH agent configured in .zshrc"
    fi
}

show_github_key_instructions() {
    local user_info
    user_info=$(get_user_info)
    local target_home="${user_info#*:}"
    
    if [ ! -f "$target_home/.ssh/id_ed25519.pub" ]; then
        return 0
    fi
    
    echo ""
    log_info "=== Add SSH Key to GitHub ==="
    echo "1. Copy your public key:"
    echo "   cat ~/.ssh/id_ed25519.pub | xclip -selection clipboard"
    echo ""
    echo "2. Go to: https://github.com/settings/keys"
    echo "3. Click 'New SSH key'"
    echo "4. Paste your key and save"
    echo ""
    echo "Or use GitHub CLI:"
    echo "   gh ssh-key add ~/.ssh/id_ed25519.pub --title \"$(hostname)\""
    echo ""
}

show_gitlab_key_instructions() {
    local user_info
    user_info=$(get_user_info)
    local target_home="${user_info#*:}"
    
    if [ ! -f "$target_home/.ssh/id_ed25519.pub" ]; then
        return 0
    fi
    
    echo ""
    log_info "=== Add SSH Key to GitLab ==="
    echo "1. Copy your public key:"
    echo "   cat ~/.ssh/id_ed25519.pub | xclip -selection clipboard"
    echo ""
    echo "2. Go to: https://gitlab.com/-/profile/keys"
    echo "3. Paste your key and save"
    echo ""
}

test_ssh_connection() {
    local service="$1"
    
    log_info "Testing SSH connection to $service..."
    
    case "$service" in
        github)
            if ssh -T git@github.com 2>&1 | grep -q "successfully authenticated"; then
                log_success "GitHub SSH connection successful"
                return 0
            else
                log_warn "GitHub SSH connection failed or not configured"
                return 1
            fi
            ;;
        gitlab)
            if ssh -T git@gitlab.com 2>&1 | grep -q "Welcome to GitLab"; then
                log_success "GitLab SSH connection successful"
                return 0
            else
                log_warn "GitLab SSH connection failed or not configured"
                return 1
            fi
            ;;
    esac
}

setup_ssh_automation() {
    log_info "Setting up SSH automation..."
    
    generate_ssh_key
    configure_ssh_client
    setup_ssh_agent
    
    # Show instructions
    if ask_permission "Show GitHub SSH key setup instructions?"; then
        show_github_key_instructions
    fi
    
    if ask_permission "Show GitLab SSH key setup instructions?"; then
        show_gitlab_key_instructions
    fi
    
    log_success "SSH automation complete"
    mark_installed "ssh_automation" "configured"
}
